[package]
name = "xx-hash"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "xxHash implementation"
authors = ["mztikk <mztikk@outlook.de>"]
repository = "https://github.com/mztikk/xx-hash"
homepage = "https://github.com/mztikk/xx-hash"
tags = ["hash", "xxhash"]
